CREATE TABLE IF NOT EXISTS entries (
    id SERIAL PRIMARY KEY,
    work TEXT NOT NULL,
    struggle TEXT NOT NULL,
    intention TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
